name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        working-directory: './client'
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Install deps
        run: yarn

      - name: Run tests
        run: yarn run test
